# Generated by Django 5.0.6 on 2024-06-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('host', models.CharField(db_collation='ascii_general_ci', db_column='Host', max_length=255, primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='User', max_length=32)),
                ('select_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Select_priv', max_length=1)),
                ('insert_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Insert_priv', max_length=1)),
                ('update_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Update_priv', max_length=1)),
                ('delete_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Delete_priv', max_length=1)),
                ('create_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Create_priv', max_length=1)),
                ('drop_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Drop_priv', max_length=1)),
                ('reload_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Reload_priv', max_length=1)),
                ('shutdown_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Shutdown_priv', max_length=1)),
                ('process_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Process_priv', max_length=1)),
                ('file_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='File_priv', max_length=1)),
                ('grant_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Grant_priv', max_length=1)),
                ('references_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='References_priv', max_length=1)),
                ('index_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Index_priv', max_length=1)),
                ('alter_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Alter_priv', max_length=1)),
                ('show_db_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Show_db_priv', max_length=1)),
                ('super_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Super_priv', max_length=1)),
                ('create_tmp_table_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Create_tmp_table_priv', max_length=1)),
                ('lock_tables_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Lock_tables_priv', max_length=1)),
                ('execute_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Execute_priv', max_length=1)),
                ('repl_slave_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Repl_slave_priv', max_length=1)),
                ('repl_client_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Repl_client_priv', max_length=1)),
                ('create_view_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Create_view_priv', max_length=1)),
                ('show_view_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Show_view_priv', max_length=1)),
                ('create_routine_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Create_routine_priv', max_length=1)),
                ('alter_routine_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Alter_routine_priv', max_length=1)),
                ('create_user_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Create_user_priv', max_length=1)),
                ('event_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Event_priv', max_length=1)),
                ('trigger_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Trigger_priv', max_length=1)),
                ('create_tablespace_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Create_tablespace_priv', max_length=1)),
                ('ssl_type', models.CharField(db_collation='utf8mb3_general_ci', max_length=9)),
                ('ssl_cipher', models.TextField()),
                ('x509_issuer', models.TextField()),
                ('x509_subject', models.TextField()),
                ('max_questions', models.PositiveIntegerField()),
                ('max_updates', models.PositiveIntegerField()),
                ('max_connections', models.PositiveIntegerField()),
                ('max_user_connections', models.PositiveIntegerField()),
                ('plugin', models.CharField(max_length=64)),
                ('authentication_string', models.TextField(blank=True, null=True)),
                ('password_expired', models.CharField(db_collation='utf8mb3_general_ci', max_length=1)),
                ('password_last_changed', models.DateTimeField(blank=True, null=True)),
                ('password_lifetime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('account_locked', models.CharField(db_collation='utf8mb3_general_ci', max_length=1)),
                ('create_role_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Create_role_priv', max_length=1)),
                ('drop_role_priv', models.CharField(db_collation='utf8mb3_general_ci', db_column='Drop_role_priv', max_length=1)),
                ('password_reuse_history', models.PositiveSmallIntegerField(blank=True, db_column='Password_reuse_history', null=True)),
                ('password_reuse_time', models.PositiveSmallIntegerField(blank=True, db_column='Password_reuse_time', null=True)),
                ('password_require_current', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Password_require_current', max_length=1, null=True)),
                ('user_attributes', models.JSONField(blank=True, db_column='User_attributes', null=True)),
            ],
            options={
                'db_table': 'user',
                'db_table_comment': 'Users and global privileges',
                'managed': False,
            },
        ),
    ]
